<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <VersionPrefix>1.0.1</VersionPrefix>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <ApplicationIcon>Assets/WarMusic.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>WarMusic</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.4.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets/WarMusic.png" />
    <Resource Include="Assets/WarMusic.ico" />
    <EmbeddedResource Include="../../docs/SETUP.md" Link="docs/SETUP.md" LogicalName="WarMusic.Docs.SETUP.md" />
  </ItemGroup>
</Project>



